[project]
name = "peritoneal-cancer-radiomics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru",
    "ruamel.yaml==0.17.40",
    "totalsegmentator==2.11.0",
    "pyradiomics",
    "pandas>=2.2.2",
    "numpy>=1.26.4",
    "SimpleITK>=2.3.1",
    "matplotlib>=3.9.2",
]

[tool.uv.sources]
pyradiomics = { path = "vendor/pyradiomics-3.1.0" }
